apiVersion: v1
kind: Endpoints
metadata:
  name: glusterfs-cluster
subsets:
- addresses:
  - ip: 192.168.3.2
  ports:
  - port: 1990
    protocol: TCP
- addresses:
  - ip: 192.168.3.4
  ports:
  - port: 1990
    protocol: TCP
---
#apiVersion: v1
#kind: Service
#metadata:
#  name: glusterfs
#  namespace: default
#spec:
#  ports:
#  - port: 1900
#    protocol: TCP
#    targetPort: 1900
#  sessionAffinity: None
#  type: ClusterIP

apiVersion: v1
kind: Service
metadata:
  name: glusterfs-cluster
spec:
  ports:
  - port: 1990 
